# Site settings
name: Bowen Zhao
email: bz142@georgetown.edu
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Python, R, Machine Learning, Deep Learning, NLP, Tensorflow, Keras"
skills: "Matehmatics Graduate in Georgetown University, in Washington. DC"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/bowen-zhao-39251b174/
  - title: medium
    url: 
  - title: github
    url: https://github.com/bowenzhao123
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
